---
threshold: 98.1
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: false
    exclude: []
  ExampleTag:
    enabled: false
    exclude:
      - Hexp::Nokogiri::Equality#call
      - Hexp::Nokogiri::Equality#equal_class?
      - Hexp::Nokogiri::Equality#equal_name?
      - Hexp::Nokogiri::Equality#equal_children?
      - Hexp::Nokogiri::Equality#compare_children
      - Hexp::Nokogiri::Equality#equal_attributes?
      - Hexp::Nokogiri::Equality#equal_text?
  ReturnTag:
    enabled: true
    exclude: []
  Summary::Presence:
    enabled: true
    exclude: []
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
